name: Benchmark
on:
  pull_request:
    branches:
      - main
permissions:
  pull-requests: write    # action needs to post a comment

jobs:
  benchmark:
    name: Julia ${{ matrix.version }} - ${{ matrix.platform.os }} - ${{ matrix.platform.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: ubuntu-latest
            arch: x64
          - os: ubuntu-24.04-arm
            arch: aarch64
        version:
          - '1'
          - 'lts'
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.platform.arch }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - name: Run benchmark
        run: |
          julia --project=benchmark -e 'import Pkg; Pkg.develop(path="."); Pkg.instantiate()'
          julia --project=benchmark benchmark/benchmarks.jl benchmark/output.json
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'julia'
          output-file-path: benchmark/output.json
          benchmark-data-dir-path: benchmark-action/dev/bench
          gh-pages-branch: bench-pages
          github-token: ${{ secrets.GITHUB_TOKEN }}
          summary-always: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
